#!/usr/bin/env bash
# Add error page location
sudo apt-get update
sudo apt-get install -y nginx 
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html


echo "Ceci n'est pas une page" > whoops-404.html
sudo mv whoops-404.html /var/www/html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://start.spring.io;
   }
   error_page 404 /whoops-404.html;
   location = /whoops-404.html{
      internal;
   }
}" > tmpfile
sudo mv -f tmpfile /etc/nginx/sites-available/default
sudo service nginx restart
