#!/usr/bin/env bash
# Configure custom headers for multiple NGINX servers
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Page not Found" > /usr/share/nginx/html/whoops_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com permanent;\n\n\terror_page 404 \/whoops_404.html;\n\tlocation = \/whoops_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf
service nginx start
