#!/usr/bin/env bash
# HAproxy setup and configuration
FILE="/etc/haproxy/haproxy.cfg"
apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy

cat <<EOF >> $FILE
frontend frontx
    bind 0.0.0.0:80
    default_backend backx
backend backx
    server web-01 100.25.160.191
    server web-02 52.91.178.10
EOF
service haproxy restart
