#!/usr/bin/env bash
# Displays numbers from 1 to 20 and:
#    displays 4 and then bad luck from China for the 4th loop iteration
#    displays 9 and then bad luck from Japan for the 9th loop iteration
#    displays 17 and then bad luck from Italy for the 17th loop iteration


n=1
while [ $n -le 20 ]
do
	case $n in
		4)
			printf "bad luck from China\n"
			;;
		9)
			printf "bad luck from Japan\n"
			;;
		17)
			printf "bad luck from Italy\n"
			;;
		*)
			printf "%d\n" $n
			;;
	esac
	n=$(( n + 1 )) 
done
