#!/usr/bin/env bash
# A bash script that displays the time for 12 hours and 59 minutes:
#    display hours from 0 to 12
#    display minutes from 1 to 59

hour=0;
min=1

while [ $hour -lt 12 ]
do
	printf "Hour %d\n" $hour
	while [ $min -lt 60 ]
	do
		printf "%d\n" $min
		min=$(( min + 1 )) 
	done
	hour=$(( hour + 1 ))
	min=1
done
