#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

for file in *;
do
    if [[ -f "$file" && ! "$file" =~ ^\. ]];
	then
        filename=$(echo "$file" | cut -d '-' -f 2-)
        echo "$filename"
    fi
done
