#!/usr/bin/bash
# Configure server to allow specific connections

sudo apt-get update && sudo apt-get install ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw disable
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https

echo "y" | sudo ufw enable
